### ISSUE TITLE
Overhaul 2.9 Migration and Highlight docs

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#11649]
Skim through the [2.9.0 release draft](https://github.com/playframework/playframework/releases) and check if there are notheworty things that are not yet mentioned (I think there were some things that should have made it into Highlights or Migration guide)

I think it would also be a good idea to give a forecast for the next release:
E.g. I think it's a good idea to finally drop a lot of deprecations in Play code, I think there are api's deprecated since Play 2.5 which sometimes makes live a bit hard for adding new features.

I will keep following lists updated until the releasee:

```[tasklist]
### Highlights
- [x] Drop Java 8
- [x] Java 17 is supported (also run the tests [against Java 20](https://openjdk.org/projects/jdk/20/), if the pass it's likely it wiill work with Java 21 LTS)
- [x] Require sbt 1.9
- [ ] https://github.com/playframework/playframework/pull/9936
- [ ] https://github.com/playframework/playframework/pull/10146
- [ ] https://github.com/playframework/playframework/pull/10228
- [ ] https://github.com/playframework/playframework/pull/10039
- [ ] https://github.com/playframework/playframework/pull/10270
- [ ] https://github.com/playframework/playframework/pull/10236
- [ ] https://github.com/playframework/playframework/pull/10224
- [ ] https://github.com/playframework/playframework/pull/10282
- [ ] https://github.com/playframework/playframework/pull/10956
- [x] Infrastructe: Switched to GitHub actions (from TravisCI), release by tag
- [x] akka-http 10.2.x
- [ ] https://github.com/playframework/playframework/pull/11758
- [ ] https://github.com/playframework/playframework/pull/10699
- [ ] https://github.com/playframework/playframework/pull/11805
- [ ] https://github.com/playframework/playframework/pull/11811
- [ ] https://github.com/playframework/playframework/pull/11933
```

```[tasklist]
### Migration Guide
- [ ] https://github.com/playframework/playframework/pull/10997
- [x] Mention the jnotify and java flags from the 2.8.15 release: https://github.com/playframework/playframework/releases/tag/2.8.15
- [ ] https://github.com/playframework/playframework/pull/9905
- [ ] https://github.com/playframework/playframework/pull/10225
- [ ] https://github.com/playframework/playframework/pull/11671
- [ ] https://github.com/playframework/playframework/pull/11672
- [ ] https://github.com/playframework/playframework/pull/11833
- [ ] https://github.com/playframework/playframework/pull/11079
- [x] org.fluentlenium -> io.fluentlenium package
- [ ] https://github.com/playframework/playframework/pull/10734
- [ ] https://github.com/playframework/playframework/pull/11920
```

```[tasklist]
### Forecast for next release
- [x] Dropping API's that are marked as deprecated as of Play 2.8 and older
- [x] 2.10 roadmap
- [x] More infrastructure improvements (Play release procedure with one click + deployment of docs, transfer domain to opencollective)
- [x] Recommend switching to Java 17
- [x] akka/akka-http replacement
- [ ] https://github.com/playframework/playframework/issues/9263
- [ ] https://github.com/playframework/playframework/issues/8569
- [x] Switch to Java 17? Would make live easier again
- [ ] change groupId to org.playframework or com.playframework? (also we still use "package com.typesafe.play.docs")
- [x] if we switch to Java 17 + groupId change + remove global state + remove akka would make sense to call it Play 3.0 (?)
- [x] Pekko
```

### Scala 3

TODO:

- [x] Go through the https://github.com/playframework/playframework/labels/scala3 label and see what else should be mentioned here.
- [x] Come up with better wording for `onLoadMessage` in `PlayAkkaHttpServer` related to Scala 3, see https://github.com/playframework/playframework/pull/11738#issuecomment-1490238354
- [x] Need to document https://github.com/playframework/playframework/issues/11846
- [x] Need to mention #11883
- [x] https://github.com/playframework/playframework/pull/11739#discussion_r1158035043
- [x] Mention 
```
libraryDependencies += clusterSharding
libraryDependencies += ("com.typesafe.akka" %% "akka-cluster-sharding-typed" % "2.6.20").cross(CrossVersion.for3Use2_13)
excludeDependencies += sbt.ExclusionRule("com.typesafe.akka", "akka-cluster-sharding-typed_3")
```
because it is not possible to override / replace the `clusterSharding` dependency from the akka-http sbt plugin.

**Comment by mkurz** [comment]
- [ ] Update Java 11+ requirement in https://github.com/playframework/playframework/blob/main/documentation/manual/gettingStarted/Requirements.md (see #11055)

**Comment by mkurz** [comment]
So, I am just working on this docs now anymore. Let's ship this finally.
