### ISSUE TITLE
Publish Play plugin for SBT 1.0.0

### ISSUE THREAD

**Issue by ScalaWilliam** [playframework/playframework#7261]
sbt 1.0 is now available:

http://developer.lightbend.com/blog/2017-08-11-sbt-1-0-0/index.html

The release notes are [here](http://www.scala-sbt.org/1.x/docs/sbt-1.0-Release-Notes.html) and there are also instructions on [how to migrate from 0.13](http://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html). Play needs to be [cross build for sbt 0.13 and 1.0](http://developer.lightbend.com/blog/2017-04-18-sbt-1-0-roadmap-and-beta1/#cross-building-sbt-1-0-plugin-from-sbt-0-13) so that we can support both versions for a while.

### Twirl

- [x] playframework/twirl#138
- [x] playframework/twirl#145
- [x] playframework/twirl#146
- [x] playframework/twirl#148
- [x] playframework/twirl#149
- [x] playframework/twirl#150
- [x] playframework/twirl#151

### Interplay

- [x] playframework/interplay#34
- [x] playframework/interplay#35
- [x] playframework/interplay#38

### Scala.js

- [x] scala-js/scala-js#2390

### sbt-web plugins

- [ ] sbt/sbt-coffeescript#20
- [ ] sbt/sbt-jshint#40
- [ ] sbt/sbt-rjs#81
- [x] sbt/sbt-web#158
- [x] sbt/sbt-web#159
- [x] sbt/sbt-digest#27
- [x] sbt/sbt-gzip#16
- [x] sbt/sbt-less#97
- [x] sbt/sbt-mocha#21
- [x] sbt/sbt-stylus#13
- [x] sbt/sbt-uglify#27
- [x] sbt/sbt-js-engine#58

### Others

- [ ] playframework/play-ebean#134

**Comment by wsargent** [comment]
@ScalaWilliam would you have time to put a PR together?

**Comment by wsargent** [comment]
See also https://github.com/jrudolph/sbt-cross-building

**Comment by wsargent** [comment]
And https://github.com/scalacenter/sbt-migration-rewrites

**Comment by ScalaWilliam** [comment]
@wsargent thanks! I'd love to do it but my time is a little limited :(

**Comment by wsargent** [comment]
This isn't happening until Scala.js can get updated, unfortunately.

**Comment by nafg** [comment]
I guess that means when https://github.com/scala-js/scala-js/issues/3065 is closed?

**Comment by sjrd** [comment]
Scala.js 0.6.19 is now published, with support for sbt 1.0.0-RC2 and following.

**Comment by SethTisue** [comment]
anyone interested in this will want to subscribe to #7366 as well

**Comment by wsargent** [comment]
Looks like a dependency on interplay now...

**Comment by Daxten** [comment]
https://github.com/playframework/interplay/pull/32

is the ticket for that, which seems pretty much ready

**Comment by etspaceman** [comment]
Looks like the interplay issue was merged today. Very exciting.

**Comment by jroper** [comment]
Whoever works on this, don't hesitate to get into contact with me, I've now made about 10 sbt plugins cross build, and am familiar with most of the ways that incompatibilities can arise.

**Comment by wsargent** [comment]
interplay work is on https://github.com/playframework/interplay/pull/34 but needs publishing

**Comment by wwbakker** [comment]
All of the dependencies mentioned by the original poster seem to be done.

**Comment by megri** [comment]
Tangentially, there is an [open issue](https://github.com/sbt/sbt/issues/3527) with SBT that causes triggered reloads to preform very poorly on macos. It would be nice to consider this before defaulting to SBT 1.0+

**Comment by godenji** [comment]
> It would be nice to consider this before defaulting to SBT 1.0+

@megri there is no default, it's up to the user (i.e. sbt version in `build.properties` will determine play 0.13 or 1.0).

**Comment by schmitch** [comment]
also triggered reloads are not a problem on play since, play uses his own reload technique.

**Comment by ArkadyKarev** [comment]
Looks like @noisycr1cket's subprojects is not supported anymore, unfortunately. Is there an option to change contributor?
