### ISSUE TITLE
Scala 2.13 support

### ISSUE THREAD

**Issue by marcospereira** [playframework/playframework#7940]
We need to have Scala 2.13 build. This obviously depends on other libraries support Scala 2.13. The current version of Scala 2.13 is a `2.13.0-M2`, so we need to start from there and have builds for more relevant milestones.

## Dependencies

This **is not** a complete list:

### Direct dependencies:

- [x] `[merged]` `[released]` interplay playframework/interplay#37
- [x] `[merged]` `[released]` play-json playframework/play-json#115 (M2)
- [x] `[merged]` `[released]` play-json playframework/play-json#141 playframework/play-json#144 (M3)
- [x] `[merged]` `[released]` play-ws playframework/play-ws#247 (M3)
- [x] `[merged]` cachecontrol playframework/cachecontrol#22 (M2)
- [x] `[merged]` `[released]` cachecontrol playframework/cachecontrol#24 (M3)
- [x] `[merged]` `[released]` twirl playframework/twirl/pull/157 (M2)
- [x] `[merged]` `[released]` twirl playframework/twirl/pull/167 (M3)
- [x] scala-java8-compat scala/scala-java8-compat#98

### Akka & Akka HTTP

Including transitive dependencies.

- [x] `[merged]` `[unreleased]` ssl-config typesafehub/ssl-config#63
- [x] `[merged]` `[unreleased]` scala-stm nbronson/scala-stm#54
- [x] `[merged]` `[released]` spray-json spray/spray-json#225 spray/spray-json#238
- [x] specs2 etorreborre/specs2#601 (it is possible to use 4.0.1)
- [x] kind-projector (this is a specs2 dep) non/kind-projector#55

**Comment by SethTisue** [comment]
the Scala community build doesn't build 100% of Play, but the parts we do build are a good initial target. here is the community build's view of a small sample Play app's transitive dependencies (transitively including test dependencies): 

`[info] Project play-webgoat`
`[info]   depends on: akka-actor, akka-http, akka-more, cachecontrol, genjavadoc, kind-projector, macro-compat, macro-paradise, pcplod, play-core, play-json, play-ws, scala, scala-java8-compat, scala-parser-combinators, scalacheck, scalatest, scalaz, shapeless, specs2, spray-json, ssl-config, twirl`

**Comment by marcospereira** [comment]
Thank you, @SethTisue!

**Comment by SethTisue** [comment]
Scala 2.13.0-M3 is now out.

**Comment by SethTisue** [comment]
akka-actor and akka-http have been published for 2.13.0-M3

**Comment by marcospereira** [comment]
Hey @SethTisue,

We also make some moves here and the following modules have been published for 2.13.0-M3:

- Play JSON 2.6.9
- Play WS 2.0.0-M1
- Twirl 1.3.15

We also now have interplay 2.0.0 with Scala 2.13.0-M3 added to `crossScalaVersions`. Play is the next in line. ;-)

**Comment by SethTisue** [comment]
@marcospereira awesome! scala/make-release-notes@db7fb47372fd4d2c7db91d8a1e3481cf32544d4b

**Comment by dwijnand** [comment]
Duplicate of #8857
