### ISSUE TITLE
Incremental refactoring of request processing pipeline

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#8005]
There are some changes we can make to play that will make request processing simpler and more maintainable without breaking things for users. These aren't changes to Play's HTTP model, just changes to how it accepts requests and serves results. Ideally we can make these changes incrementally, in simple stages. An ordering for changes is given below.

**Stage 1** - _move request processing into `DefaultHttpRequestHandler`_

This change moves logic out of the server code and into the `DefaultHttpRequestHandler`. This remove duplication, but most importantly it centralises the logic in one method instead of a dozen methods. This makes the code more understandable and makes it easier to refactor in _Stage 2_ below.

- [ ] #7986. Move `WebCommands` out of `ApplicationProvider` interface - moves logic out of [`Server`](https://github.com/playframework/playframework/blob/8ca509d1f2c31c2ce678acd2a4e07a1799816a08/framework/src/play-server/src/main/scala/play/core/server/Server.scala#L56)
- [ ] Move `RequestFactory` into `DefaultHttpRequestHandler` - moves logic out of [`Server`](https://github.com/playframework/playframework/blob/8ca509d1f2c31c2ce678acd2a4e07a1799816a08/framework/src/play-server/src/main/scala/play/core/server/Server.scala#L68-L69) out of this `Server` object
- [ ] Move `ForwardedHeaderHandler` into `DefaultRequestHandler` - moves duplicated logic out of [`AkkaModelConversion`](https://github.com/playframework/playframework/blob/8ca509d1f2c31c2ce678acd2a4e07a1799816a08/framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala#L96-L103) and [`NettyModelConversion`](https://github.com/playframework/playframework/blob/8ca509d1f2c31c2ce678acd2a4e07a1799816a08/framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala#L94)

**Stage 2** - _refactor request logic in `DefaultHttpRequestHandler`_

At this point logic has been moved out of the server classes and moved into `DefaultHttpRequestHandler`. We can now see most of the request processing logic in one place and look at refactoring it.

As an example, we could move to a model like the following:
https://gist.github.com/richdougherty/35694e699777019728f9a07b36f17fd5

- [ ] Make a something like filters, but which runs for every request, not just requests that are routed to actions.
- [ ] Refactor `WebCommands`, `RequestFactory` and `ForwardedHeaderHandler` to use this logic.
- [ ] Change `EvolutionsWebCommand` to use this new pipeline instead of registering with the `WebCommands`. (Since #7986 the `BuildContext` object Evolutions needs is available in the `DevContext` object.)
- [ ] Deprecate `WebCommands`.

**Stage 3** - _ideas for other improvements_

After Stage 2 is completed we're left with a simpler request processing pipeline. We can stop once we've completed Stage 2 or we can explore further. Below is a list of general thoughts, questions and ideas for improving the request pipeline further. The list is based on my own impressions areas where Play could improve, either because there is low-hanging fruit or because there are warts in the Play code that would be nice to remove.

- `Action` and `WebCommand` are both functions from `RequestHeader => X` could we generalise this into the idea of a `Handler` which accepts a `RequestHeader` and returns another `Handler`? We could introduce handler results that represent an `Accumulator[ByteString,Result]` and a `Flow[Message,Message,_]`. If making changes here, consider how it might affect a Java API in the future.
- `Routes` take a `RequestHeader` and optionally returns a `Handler` (because `Routes` has a `PartialFunction`. This seems very similar to other request pipeline stages which take a `RequestHeader` then optionally process it (e.g. `EvolutionsWebCommand`). Could/should we unify these?
- Could we somehow get the `ServerResultUtils` logic out of the `Server` and make it a part of the request pipeline that runs just before a result is sent? The `ServerResultUtils` object is a bit weird because it's one of the few dependencies that a `Server` has on an `Application` and it would be good to remove it. There is also a lot of duplicated logic between Akka HTTP and Netty.
- The `Server` doesn't really need a full `Application` object, it just needs an `HttpRequestHandler` and a function it can call to close the application. (With the exception of `ServerResultUtils` mentioned above.)
- The reloading `ApplicationProvider` could be changed to an `HttpRequestHandler` which either serves up a compile error or delegates to an `Application`'s instantiated `HttpRequestHandler`.
- Instead of calling `HttpErrorHandler` directly to render an error could the `Result` or `Handler` type be extended to include the idea of a `ServerErrorResult` and a `ClientErrorResult`. Then actions/filters could return this type of result and it would be able to be modified and processed by elements in the request pipeline. The final element in the pipeline could use the `HttpErrorHandler` to turn these object types into a concrete `Result`.

**Comment by schmitch** [comment]
if you start with `Move ForwardedHeaderHandler into DefaultRequestHandler - moves duplicated logic out of AkkaModelConversion and NettyModelConversion`  it would be great if you could ping me, because I'm actually creating a Conversion method for Servlet's.

**Comment by richdougherty** [comment]
@schmitch sure will ping you. I don't think this is something I'll be working on anytime soon anyway because there are other priorities at the moment.

**Comment by richdougherty** [comment]
@schmitch sure will ping you. I don't think this is something I'll be working on anytime soon anyway because there are other priorities at the moment.

**Comment by richdougherty** [comment]
I created an issue for HttpRequestHandler API improvements: #8278. We should keep this in mind when making any changes.

**Comment by ashleymercer** [comment]
> Make a something like filters, but which runs for every request, not just requests that are routed to actions.

This would be *incredibly* powerful since it would simplify e.g. tracing. Related bug in kamon: https://github.com/kamon-io/kamon-play/issues/17
